// Generated by Wrangler by running `wrangler types`

interface Env {
	GOOGLE_MAPS_API_KEY: string;
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
	DATABASE_URL: string;
	SESSION_SECRET: string;
	ASSETS: Fetcher;
}
