#:schema node_modules/wrangler/config-schema.json
name = "hyperlocal-web"
account_id = "91ff95bcb91fbfa1b1c5c356262b1fe4"

main = "./server.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-04-01"

assets = { directory = "./build/client", binding = "ASSETS", html_handling = "drop-trailing-slash" }

routes = [
  { pattern = "tokyo.hyper-local.app", custom_domain = true },
]

[observability]
enabled = true
