import type { Place } from '@hyper-local/types'

const placeTypeLabelMap: Record<string, string> = {
  amusement_center: 'amusement center',
  amusement_park: 'amusement park',
  aquarium: 'aquarium',
  banquet_hall: 'banquet hall',
  bowling_alley: 'bowling',
  casino: 'casino',
  community_center: 'community center',
  convention_center: 'convention center',
  cultural_center: 'cultural center',
  event_venue: 'event venue',
  hiking_area: 'hiking',
  historical_landmark: 'historical landmark',
  marina: 'marina',
  movie_theater: 'movie theater',
  national_park: 'national park',
  night_club: 'night club',
  park: 'park',
  tourist_attraction: 'tourist attraction',
  visitor_center: 'visitor center',
  zoo: 'zoo',
  american_restaurant: 'american',
  bakery: 'bakery',
  bar: 'bar',
  barbecue_restaurant: 'barbecue',
  brazilian_restaurant: 'brazilian',
  breakfast_restaurant: 'breakfast',
  brunch_restaurant: 'brunch',
  cafe: 'cafe',
  chinese_restaurant: 'chinese',
  coffee_shop: 'coffee',
  fast_food_restaurant: 'fast food',
  french_restaurant: 'french',
  greek_restaurant: 'greek',
  hamburger_restaurant: 'hamburger',
  ice_cream_shop: 'ice cream',
  indian_restaurant: 'indian',
  indonesian_restaurant: 'indonesian',
  italian_restaurant: 'italian',
  japanese_restaurant: 'japanese',
  korean_restaurant: 'korean',
  lebanese_restaurant: 'lebanese',
  mediterranean_restaurant: 'mediterranean',
  mexican_restaurant: 'mexican',
  middle_eastern_restaurant: 'middle eastern',
  pizza_restaurant: 'pizza',
  ramen_restaurant: 'ramen',
  sandwich_shop: 'sandwich',
  seafood_restaurant: 'seafood',
  spanish_restaurant: 'spanish',
  steak_house: 'steak',
  sushi_restaurant: 'sushi',
  thai_restaurant: 'thai',
  turkish_restaurant: 'turkish',
  vegan_restaurant: 'vegan',
  vegetarian_restaurant: 'vegetarian',
  vietnamese_restaurant: 'vietnamese',

  book_store: 'book',
  cell_phone_store: 'cell phone',
  clothing_store: 'clothing',
  convenience_store: 'convenience',
  department_store: 'department',
  discount_store: 'discount',
  electronics_store: 'electronics',
  furniture_store: 'furniture',
  gift_shop: 'gift',
  grocery_store: 'grocery',
  hardware_store: 'hardware',
  home_goods_store: 'home goods',
  home_improvement_store: 'home improvement',
  jewelry_store: 'jewelry',
  liquor_store: 'liquor',
  market: 'market',
  pet_store: 'pet',
  shoe_store: 'shoe',
  shopping_mall: 'mall',
  sporting_goods_store: 'sporting goods',
  supermarket: 'supermarket',
  wholesaler: 'wholesaler',
  drugstore: 'drugstore',
  spa: 'spa',
  airport: 'airport',
  bus_station: 'bus',
  bus_stop: 'bus',
  subway_station: 'subway',
  taxi_stand: 'taxi',
  train_station: 'train',
}
// 表示する Badge をフィルタ
export const mapPlaceTypes = (types: Place['types']) => {
  return types
    .filter((type) => Object.keys(placeTypeLabelMap).includes(type))
    .map((type: string) => placeTypeLabelMap[type] ?? '')
}
