packages:
  - ./apps/*
  - ./packages/*
catalog:
  "@ai-sdk/google": 1.0.12
  "@biomejs/biome": 1.9.4
  "@clerk/react-router": 0.1.5
  "@conform-to/react": 1.2.2
  "@conform-to/zod": 1.2.2
  "@date-fns/tz": 1.2.0
  "@date-fns/utc": 2.1.0
  "@libsql/client": 0.14.0
  "@libsql/kysely-libsql": 0.4.1
  "@radix-ui/react-checkbox": 1.1.3
  "@radix-ui/react-collapsible": 1.1.2
  "@radix-ui/react-dialog": 1.1.4
  "@radix-ui/react-dropdown-menu": 2.1.4
  "@radix-ui/react-label": 2.1.1
  "@radix-ui/react-popover": 1.1.4
  "@radix-ui/react-radio-group": 1.2.2
  "@radix-ui/react-select": 2.1.4
  "@radix-ui/react-slider": 1.2.2
  "@radix-ui/react-slot": 1.1.1
  "@radix-ui/react-tabs": 1.1.2
  "@react-router/dev": 7.1.1
  "@react-router/node": 7.1.1
  "@react-router/remix-routes-option-adapter": 7.1.1
  "@react-router/serve": 7.1.1
  "@types/debug": 4.1.12
  "@types/node": 22.10.5
  "@types/nprogress": 0.2.3
  "@types/react": 19.0.3
  "@types/react-dom": 19.0.2
  accept-language: 3.0.20
  ai: 4.0.27
  autoprefixer: 10.4.20
  class-variance-authority: 0.7.1
  cleye: 1.3.2
  clsx: 2.1.1
  concurrently: 9.1.2
  crawlee: 3.12.1
  date-fns: 4.1.0
  debug: 4.4.0
  dotenv: 16.4.7
  dotenv-cli: 7.4.4
  duckdb: 1.1.3
  embla-carousel-react: 8.5.1
  isbot: 5.1.20
  kysely: 0.27.5
  kysely-duckdb: 0.1.0
  lucide-react: 0.469.0
  nanoid: 5.0.9
  next-themes: 0.4.4
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  postcss: 8.4.49
  prettier: 3.4.2
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-tailwindcss: 0.6.9
  prisma: 6.1.0
  prisma-kysely: 1.8.0
  react: 19.0.0
  react-dom: 19.0.0
  react-router: 7.1.1
  react-twc: 1.4.2
  remix-flat-routes: 0.6.5
  remix-toast: 2.0.0
  remix-utils: 8.0.0
  sonner: 1.7.1
  tailwind-merge: 2.6.0
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.6.0
  tsx: 4.19.2
  turbo: 2.3.3
  typescript: 5.7.2
  vite: 6.0.7
  vite-tsconfig-paths: 5.1.4
  vitest: 2.1.8
  zod: 3.24.1
  zodix: 0.4.4
