packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@ai-sdk/google': 2.0.33
  '@biomejs/biome': 2.3.5
  '@clerk/react-router': 2.2.1
  '@coji/zodix': 0.7.0
  '@conform-to/react': 1.13.3
  '@conform-to/zod': 1.13.3
  '@date-fns/tz': 1.4.1
  '@date-fns/utc': 2.1.1
  '@libsql/client': 0.15.15
  '@libsql/kysely-libsql': 0.4.1
  '@react-router/dev': 7.9.6
  '@react-router/node': 7.9.6
  '@react-router/remix-routes-option-adapter': 7.9.6
  '@react-router/serve': 7.9.6
  '@tailwindcss/vite': 4.1.17
  '@types/debug': 4.1.12
  '@types/node': 24.10.1
  '@types/nprogress': 0.2.3
  '@types/react': 19.2.5
  '@types/react-dom': 19.2.3
  accept-language: 3.0.20
  ai: 5.0.93
  autoprefixer: 10.4.22
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  concurrently: 9.2.1
  crawlee: 3.15.3
  date-fns: 4.1.0
  debug: 4.4.3
  dotenv: 17.2.3
  dotenv-cli: 11.0.0
  duckdb: 1.4.2
  embla-carousel-react: 8.6.0
  isbot: 5.1.32
  kysely: 0.28.8
  kysely-duckdb: 0.1.0
  lucide-react: 0.553.0
  mdx-bundler: 10.1.1
  minio: 8.0.6
  nanoid: 5.1.6
  next-themes: 0.4.6
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  postcss: 8.5.3
  prettier: 3.6.2
  prettier-plugin-organize-imports: 4.3.0
  prettier-plugin-tailwindcss: 0.7.1
  prisma: 6.19.0
  prisma-kysely: 2.2.1
  radix-ui: 1.4.3
  react: 19.2.0
  react-dom: 19.2.0
  react-router: 7.9.6
  react-twc: 1.5.1
  rehype-highlight: 7.0.2
  remark-gfm: 4.0.1
  remix-flat-routes: 0.8.5
  remix-toast: 3.3.0
  remix-utils: 9.0.0
  sonner: 2.0.7
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.9.0
  tsx: 4.20.6
  turbo: 2.6.1
  typescript: 5.9.3
  vite: 7.2.2
  vite-tsconfig-paths: 5.1.4
  vitest: 4.0.9
  zod: 4.1.12

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - duckdb
  - esbuild
  - prisma
  - workerd
