packages:
  - ./apps/*
  - ./packages/*
catalog:
  '@ai-sdk/google': 0.0.55
  '@biomejs/biome': 1.9.4
  '@coji/remix-auth-google': 3.0.3
  '@conform-to/react': 1.2.2
  '@conform-to/zod': 1.2.2
  '@date-fns/tz': 1.2.0
  '@date-fns/utc': 2.1.0
  '@libsql/client': 0.14.0
  '@libsql/kysely-libsql': 0.4.1
  '@radix-ui/react-checkbox': 1.1.2
  '@radix-ui/react-collapsible': 1.1.1
  '@radix-ui/react-dialog': 1.1.2
  '@radix-ui/react-dropdown-menu': 2.1.2
  '@radix-ui/react-label': 2.1.0
  '@radix-ui/react-popover': 1.1.2
  '@radix-ui/react-radio-group': 1.2.1
  '@radix-ui/react-select': 2.1.2
  '@radix-ui/react-slider': 1.2.1
  '@radix-ui/react-slot': 1.1.0
  '@radix-ui/react-tabs': 1.1.1
  '@react-router/dev': 7.0.0-pre.5
  '@react-router/node': 7.0.0-pre.5
  '@react-router/remix-routes-option-adapter': 7.0.0-pre.5
  '@react-router/serve': 7.0.0-pre.5
  '@remix-run/dev': 2.14.0
  '@remix-run/node': 2.14.0
  '@remix-run/react': 2.14.0
  '@remix-run/serve': 2.14.0
  '@remix-run/server-runtime': 2.14.0
  '@types/debug': 4.1.12
  '@types/node': 22.9.0
  '@types/nprogress': 0.2.3
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  '@vercel/remix': 2.13.1
  accept-language: 3.0.20
  ai: 3.4.33
  autoprefixer: 10.4.20
  class-variance-authority: 0.7.0
  cleye: 1.3.2
  clsx: 2.1.1
  concurrently: 9.1.0
  crawlee: 3.12.0
  date-fns: 4.1.0
  debug: 4.3.7
  dotenv: 16.4.5
  duckdb: 1.1.1
  embla-carousel-react: 8.3.1
  kysely: 0.27.4
  kysely-duckdb: 0.1.0
  lucide-react: 0.456.0
  nanoid: 5.0.8
  next-themes: 0.4.3
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  postcss: 8.4.47
  prettier: 3.3.3
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-tailwindcss: 0.6.8
  prisma: 5.22.0
  prisma-kysely: 1.8.0
  react: 18.3.1
  react-router: 7.0.0-pre.2
  react-router-dom: 7.0.0-pre.2
  react-twc: 1.4.2
  remix-auth: 3.7.0
  remix-auth-oauth2: 2.4.0
  remix-flat-routes: 0.6.5
  remix-toast: 1.2.2
  remix-utils: 7.7.0
  sonner: 1.7.0
  tailwind-merge: 2.5.4
  tailwindcss: 3.4.14
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.5.0
  tsx: 4.19.2
  turbo: 2.2.3
  typescript: 5.6.3
  vite: 5.4.10
  vite-tsconfig-paths: 5.1.1
  vitest: 2.1.4
  zod: 3.23.8
  zodix: 0.4.4
