packages:
  - ./apps/*
  - ./packages/*
catalog:
  '@ai-sdk/google': 1.2.17
  '@biomejs/biome': 1.9.4
  '@clerk/react-router': 1.4.1
  '@conform-to/react': 1.5.0
  '@conform-to/zod': 1.5.0
  '@date-fns/tz': 1.2.0
  '@date-fns/utc': 2.1.0
  '@libsql/client': 0.15.4
  '@libsql/kysely-libsql': 0.4.1
  '@radix-ui/react-checkbox': 1.3.1
  '@radix-ui/react-collapsible': 1.1.10
  '@radix-ui/react-dialog': 1.1.13
  '@radix-ui/react-dropdown-menu': 2.1.14
  '@radix-ui/react-label': 2.1.6
  '@radix-ui/react-popover': 1.1.13
  '@radix-ui/react-radio-group': 1.3.6
  '@radix-ui/react-select': 2.2.4
  '@radix-ui/react-slider': 1.3.4
  '@radix-ui/react-slot': 1.2.2
  '@radix-ui/react-tabs': 1.1.11
  '@react-router/dev': 7.5.3
  '@react-router/node': 7.5.3
  '@react-router/remix-routes-option-adapter': 7.5.3
  '@react-router/serve': 7.5.3
  '@tailwindcss/vite': 4.1.5
  '@types/debug': 4.1.12
  '@types/node': 22.15.15
  '@types/nprogress': 0.2.3
  '@types/react': 19.1.3
  '@types/react-dom': 19.1.3
  accept-language: 3.0.20
  ai: 4.3.15
  autoprefixer: 10.4.21
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  concurrently: 9.1.2
  crawlee: 3.13.3
  date-fns: 4.1.0
  debug: 4.4.0
  dotenv: 16.5.0
  dotenv-cli: 8.0.0
  duckdb: 1.2.1
  embla-carousel-react: 8.6.0
  isbot: 5.1.27
  kysely: 0.28.2
  kysely-duckdb: 0.1.0
  lucide-react: 0.508.0
  nanoid: 5.1.5
  next-themes: 0.4.6
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  postcss: 8.5.3
  prettier: 3.5.3
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-tailwindcss: 0.6.11
  prisma: 6.7.0
  prisma-kysely: 1.8.0
  react: 19.1.0
  react-dom: 19.1.0
  react-router: 7.5.3
  react-twc: 1.4.2
  remix-flat-routes: 0.8.5
  remix-toast: 3.1.0
  remix-utils: 8.5.0
  sonner: 2.0.3
  tailwind-merge: 3.2.0
  tailwindcss: 4.1.5
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.7.0
  tsx: 4.19.4
  turbo: 2.5.3
  typescript: 5.7.3
  vite: 6.3.5
  vite-tsconfig-paths: 5.1.4
  vitest: 3.1.3
  zod: 3.24.4
  zodix: 0.4.4
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - '@prisma/engines'
  - duckdb
  - esbuild
  - prisma
  - workerd
