/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: Generated<string>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: Generated<string>;
  userId: string;
}

export interface AreaArticles {
  areaId: string;
  cityId: string;
  compiledCode: string;
  content: string;
  createdAt: Generated<string>;
  id: string;
  language: string;
  metadata: string;
  sceneId: string;
  status: Generated<string>;
  title: string;
  updatedAt: string;
}

export interface LocalizedPlaces {
  areaId: string;
  categoryId: string;
  cityId: string;
  createdAt: Generated<string>;
  displayName: string;
  genres: Generated<string>;
  googleMapsUri: string;
  language: string;
  latitude: number;
  longitude: number;
  originalDisplayName: string;
  photos: string;
  placeId: string;
  priceLevel: string | null;
  rankingType: string;
  rating: number;
  regularOpeningHours: string | null;
  reviews: string;
  sourceUri: string | null;
  updatedAt: Generated<string>;
  userRatingCount: number;
}

export interface PlaceListings {
  areaId: string;
  categoryId: string;
  cityId: string;
  createdAt: Generated<string>;
  placeId: string;
  rankingType: string;
  updatedAt: Generated<string>;
}

export interface Places {
  categories: Generated<string>;
  createdAt: Generated<string>;
  displayName: string;
  genres: Generated<string>;
  googleMapsUri: string;
  id: string;
  latitude: number;
  longitude: number;
  photos: string;
  priceLevel: string | null;
  rating: number;
  regularOpeningHours: string | null;
  reviews: string;
  sourceUri: string | null;
  updatedAt: Generated<string>;
  userRatingCount: number;
}

export interface Session {
  createdAt: Generated<string>;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<string>;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<string>;
  email: string;
  emailVerified: Generated<number>;
  id: string;
  image: string | null;
  name: string;
  role: Generated<string | null>;
  updatedAt: Generated<string>;
}

export interface Verification {
  createdAt: Generated<string>;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: Generated<string>;
  value: string;
}

export interface DB {
  account: Account;
  areaArticles: AreaArticles;
  localizedPlaces: LocalizedPlaces;
  placeListings: PlaceListings;
  places: Places;
  session: Session;
  user: User;
  verification: Verification;
}
