/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AdminUsers {
  createdAt: Generated<string>;
  displayName: string;
  email: string;
  id: string;
  locale: string;
  pictureUrl: string | null;
  role: Generated<string>;
  updatedAt: string;
}

export interface AreaArticles {
  areaId: string;
  cityId: string;
  compiledCode: string;
  content: string;
  createdAt: Generated<string>;
  id: string;
  language: string;
  metadata: string;
  sceneId: string;
  status: Generated<string>;
  title: string;
  updatedAt: string;
}

export interface LocalizedPlaces {
  areaId: string;
  categoryId: string;
  cityId: string;
  createdAt: Generated<string>;
  displayName: string;
  genres: Generated<string>;
  googleMapsUri: string;
  language: string;
  latitude: number;
  longitude: number;
  originalDisplayName: string;
  photos: string;
  placeId: string;
  priceLevel: string | null;
  rankingType: string;
  rating: number;
  regularOpeningHours: string | null;
  reviews: string;
  sourceUri: string | null;
  updatedAt: Generated<string>;
  userRatingCount: number;
}

export interface PlaceListings {
  areaId: string;
  categoryId: string;
  cityId: string;
  createdAt: Generated<string>;
  placeId: string;
  rankingType: string;
  updatedAt: Generated<string>;
}

export interface Places {
  categories: Generated<string>;
  createdAt: Generated<string>;
  displayName: string;
  genres: Generated<string>;
  googleMapsUri: string;
  id: string;
  latitude: number;
  longitude: number;
  photos: string;
  priceLevel: string | null;
  rating: number;
  regularOpeningHours: string | null;
  reviews: string;
  sourceUri: string | null;
  updatedAt: Generated<string>;
  userRatingCount: number;
}

export interface DB {
  adminUsers: AdminUsers;
  areaArticles: AreaArticles;
  localizedPlaces: LocalizedPlaces;
  placeListings: PlaceListings;
  places: Places;
}
