#:schema node_modules/wrangler/config-schema.json
name = "hyperlocal-admin"
account_id = "91ff95bcb91fbfa1b1c5c356262b1fe4"

main = "./workers/app.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./build/client", binding = "ASSETS", html_handling = "drop-trailing-slash" }

routes = [{ pattern = "admin.hyper-local.app", custom_domain = true }]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "hyperlocal"
database_id = "3af44920-5ced-4dde-9d22-18f3e20eada3"
